### ISSUE TITLE
Error in v0.2.19

### ISSUE THREAD

**Issue by MarkoMin** [starbelly/rebar3_ex_doc#58]
Hi, I just switched to v0.2.19 and I get the following error:
```
(FunctionClauseError) no function clause matching in ExDoc.Formatter.HTML.strip_tags/2    
    
    The following arguments were given to ExDoc.Formatter.HTML.strip_tags/2:
    
        # 1
        nil
    
        # 2
        " "
    
    (ex_doc 0.30.3) lib/ex_doc/formatter/html.ex:497: ExDoc.Formatter.HTML.strip_tags/2
    (ex_doc 0.30.3) lib/ex_doc/formatter/html/search_data.ex:146: ExDoc.Formatter.HTML.SearchData.clean_html/1
    (ex_doc 0.30.3) lib/ex_doc/formatter/html/search_data.ex:112: ExDoc.Formatter.HTML.SearchData.extract_sections/2
    (ex_doc 0.30.3) lib/ex_doc/formatter/html/search_data.ex:49: ExDoc.Formatter.HTML.SearchData.module/1
    (elixir 1.13.4) lib/enum.ex:4086: Enum.flat_map_list/2
    (ex_doc 0.30.3) lib/ex_doc/formatter/html/search_data.ex:14: ExDoc.Formatter.HTML.SearchData.create/3
    (ex_doc 0.30.3) lib/ex_doc/formatter/html.ex:235: ExDoc.Formatter.HTML.generate_search_data/3
    (ex_doc 0.30.3) lib/ex_doc/formatter/html.ex:26: ExDoc.Formatter.HTML.run/2
```

I tried to remove `extras` and `before_closing_body_tag` from configuration, but error still exist. It works when using v0.2.18.

**Comment by starbelly** [comment]
Fixed via https://github.com/elixir-lang/ex_doc/pull/1746 

Will close this when a new release of rebar3_ex_doc is cut (pending a new release of ex_doc being cut).
